<?php
session_start();
if ($_SESSION['status'] != 'valid')
{
    header("Location: index.php");
    exit();
}
?>

<div class = "container">
<p><h1><center>GET RICK ROLLED</center></h1></p>
<center><iframe width="1000" height="563" src="https://www.youtube.com/embed/dQw4w9WgXcQ?si=ZnPZsLMM5QdWU3Cf" 
    title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
    allowfullscreen>
</iframe></center>
</div>